#!/usr/bin/env bash
# SSH Server Setup Script for Ubuntu
# Installs and configures openssh-server with secure defaults

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="${DOTFILES_DIR:-$(cd "$SCRIPT_DIR/../.." && pwd)}"

source "$DOTFILES_DIR/lib/utils.sh"

# ============================================================================
# Configuration
# ============================================================================
SSHD_CONFIG="/etc/ssh/sshd_config"
SSHD_CONFIG_BACKUP="/etc/ssh/sshd_config.backup.$(date +%Y%m%d_%H%M%S)"

# Default settings
SSH_PORT=22
PERMIT_ROOT_LOGIN="no"
PASSWORD_AUTH="yes"
PUBKEY_AUTH="yes"
X11_FORWARDING="yes"
CLIENT_ALIVE_INTERVAL=60
CLIENT_ALIVE_COUNT_MAX=3

# ============================================================================
# Helper Functions
# ============================================================================

get_local_ip() {
    # Get primary local IP address
    hostname -I 2>/dev/null | awk '{print $1}' || echo "unknown"
}

check_sshd_config_syntax() {
    sudo sshd -t 2>/dev/null
    return $?
}

# ============================================================================
# Setup Functions
# ============================================================================

install_openssh_server() {
    info "Checking openssh-server..."

    if dpkg -l openssh-server &> /dev/null; then
        success "openssh-server already installed"
    else
        info "Installing openssh-server..."
        sudo apt-get update
        sudo apt-get install -y openssh-server
        success "openssh-server installed"
    fi
}

backup_sshd_config() {
    if [ -f "$SSHD_CONFIG" ]; then
        info "Backing up $SSHD_CONFIG..."
        sudo cp "$SSHD_CONFIG" "$SSHD_CONFIG_BACKUP"
        success "Backup saved to $SSHD_CONFIG_BACKUP"
    fi
}

configure_sshd() {
    info "Configuring SSH server..."

    # Create a new sshd_config with our settings
    sudo tee "$SSHD_CONFIG" > /dev/null << EOF
# SSH Server Configuration
# Generated by dotfiles setup on $(date)
# Original backup: $SSHD_CONFIG_BACKUP

# ============================================================================
# Network
# ============================================================================
Port $SSH_PORT
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

# ============================================================================
# Authentication
# ============================================================================
PermitRootLogin $PERMIT_ROOT_LOGIN
PubkeyAuthentication $PUBKEY_AUTH
PasswordAuthentication $PASSWORD_AUTH

# Disable other authentication methods
ChallengeResponseAuthentication no
KerberosAuthentication no
GSSAPIAuthentication no

# PAM (required for Ubuntu)
UsePAM yes

# ============================================================================
# Security
# ============================================================================
# Only allow specific users (uncomment and modify as needed)
# AllowUsers your_username

# Limit authentication attempts
MaxAuthTries 3
MaxSessions 10

# ============================================================================
# Session
# ============================================================================
X11Forwarding $X11_FORWARDING
PrintMotd no
PrintLastLog yes

# Accept locale environment variables
AcceptEnv LANG LC_*

# ============================================================================
# Connection Keep-Alive
# ============================================================================
# Server sends keep-alive every $CLIENT_ALIVE_INTERVAL seconds
# Disconnects after $CLIENT_ALIVE_COUNT_MAX failed attempts
ClientAliveInterval $CLIENT_ALIVE_INTERVAL
ClientAliveCountMax $CLIENT_ALIVE_COUNT_MAX
TCPKeepAlive yes

# ============================================================================
# Subsystem
# ============================================================================
Subsystem sftp /usr/lib/openssh/sftp-server
EOF

    success "SSH server configured"
}

enable_sshd_service() {
    info "Enabling and starting SSH service..."

    sudo systemctl enable ssh
    sudo systemctl restart ssh

    # Verify service is running
    if sudo systemctl is-active --quiet ssh; then
        success "SSH service is running"
    else
        error "Failed to start SSH service"
        exit 1
    fi
}

show_connection_info() {
    local ip=$(get_local_ip)

    echo ""
    echo "======================================"
    echo "  SSH Server Setup Complete!"
    echo "======================================"
    echo ""
    echo "Connection info:"
    echo "  IP Address: $ip"
    echo "  Port: $SSH_PORT"
    echo ""
    echo "Connect with:"
    echo "  ssh $(whoami)@$ip"
    if [ "$SSH_PORT" != "22" ]; then
        echo "  ssh -p $SSH_PORT $(whoami)@$ip"
    fi
    echo ""
    echo "Settings:"
    echo "  Root login: $PERMIT_ROOT_LOGIN"
    echo "  Password auth: $PASSWORD_AUTH"
    echo "  Key auth: $PUBKEY_AUTH"
    echo "  Keep-alive: ${CLIENT_ALIVE_INTERVAL}s x ${CLIENT_ALIVE_COUNT_MAX}"
    echo ""
}

# ============================================================================
# Interactive Setup
# ============================================================================

interactive_setup() {
    echo ""
    echo "======================================"
    echo "  SSH Server Setup"
    echo "======================================"
    echo ""

    # Ask for SSH port
    read -p "SSH Port [$SSH_PORT]: " input_port
    if [ -n "$input_port" ]; then
        if [[ "$input_port" =~ ^[0-9]+$ ]] && [ "$input_port" -ge 1 ] && [ "$input_port" -le 65535 ]; then
            SSH_PORT="$input_port"
        else
            warning "Invalid port, using default: $SSH_PORT"
        fi
    fi

    # Ask about password authentication
    echo ""
    echo "Password authentication:"
    echo "  yes = Allow password login (easier, less secure)"
    echo "  no  = Only allow SSH key login (secure, but ensure keys are set up first!)"
    echo ""
    read -p "Allow password authentication? [Y/n]: " input_password
    if [[ "$input_password" =~ ^[Nn] ]]; then
        PASSWORD_AUTH="no"
        warning "Password authentication will be DISABLED"
        warning "Make sure your SSH key is already in ~/.ssh/authorized_keys!"
        echo ""
        read -p "Are you sure? [y/N]: " confirm
        if [[ ! "$confirm" =~ ^[Yy] ]]; then
            PASSWORD_AUTH="yes"
            info "Keeping password authentication enabled"
        fi
    fi

    echo ""
}

# ============================================================================
# Main
# ============================================================================

main() {
    # Check if running on Linux
    if [ "$(uname -s)" != "Linux" ]; then
        error "This script is only for Linux systems"
        exit 1
    fi

    # Check for Ubuntu/Debian
    if ! command -v apt-get &> /dev/null; then
        error "This script requires apt-get (Ubuntu/Debian)"
        exit 1
    fi

    case "${1:-}" in
        --help|-h)
            echo "Usage: $0 [--defaults]"
            echo ""
            echo "Options:"
            echo "  --defaults    Use default settings without prompts"
            echo "  --help        Show this help message"
            ;;
        --defaults)
            info "Using default settings..."
            install_openssh_server
            backup_sshd_config
            configure_sshd

            # Check config syntax before restarting
            if check_sshd_config_syntax; then
                enable_sshd_service
                show_connection_info
            else
                error "SSH config syntax error! Restoring backup..."
                sudo cp "$SSHD_CONFIG_BACKUP" "$SSHD_CONFIG"
                exit 1
            fi
            ;;
        *)
            interactive_setup
            install_openssh_server
            backup_sshd_config
            configure_sshd

            # Check config syntax before restarting
            if check_sshd_config_syntax; then
                enable_sshd_service
                show_connection_info
            else
                error "SSH config syntax error! Restoring backup..."
                sudo cp "$SSHD_CONFIG_BACKUP" "$SSHD_CONFIG"
                exit 1
            fi
            ;;
    esac
}

main "$@"
