#!/usr/bin/env bash
# SSH Multi-Account Setup Script
# Detects existing SSH keys and helps configure SSH + Git for multiple accounts

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="${DOTFILES_DIR:-$(cd "$SCRIPT_DIR/../.." && pwd)}"

source "$DOTFILES_DIR/lib/utils.sh"

# ============================================================================
# Configuration
# ============================================================================
SSH_DIR="$HOME/.ssh"
GITCONFIG="$HOME/.gitconfig"

# ============================================================================
# Helper Functions
# ============================================================================

# Scan for SSH keys (excluding default id_ed25519/id_rsa)
scan_ssh_keys() {
    local keys=()

    if [ ! -d "$SSH_DIR" ]; then
        return
    fi

    # Find all private keys (files without .pub extension that have matching .pub)
    for pub_file in "$SSH_DIR"/*.pub; do
        [ -f "$pub_file" ] || continue

        local private_key="${pub_file%.pub}"
        local key_name=$(basename "$private_key")

        # Skip default keys
        if [[ "$key_name" == "id_ed25519" ]] || [[ "$key_name" == "id_rsa" ]]; then
            continue
        fi

        if [ -f "$private_key" ]; then
            keys+=("$key_name")
        fi
    done

    echo "${keys[@]}"
}

# Check if SSH config already has a host defined
has_ssh_host() {
    local host="$1"
    if [ -f "$SSH_DIR/config" ]; then
        grep -q "^Host $host$" "$SSH_DIR/config" 2>/dev/null
        return $?
    fi
    return 1
}

# Check if gitconfig has URL rewrite for organization
has_git_url_rewrite() {
    local org="$1"
    if [ -f "$GITCONFIG" ]; then
        grep -q "insteadOf.*$org" "$GITCONFIG" 2>/dev/null
        return $?
    fi
    return 1
}

# ============================================================================
# Setup Functions
# ============================================================================

setup_ssh_config_header() {
    # Create SSH config with global defaults if not exists
    if [ ! -f "$SSH_DIR/config" ]; then
        info "Creating SSH config with default settings..."

        cat > "$SSH_DIR/config" << 'EOF'
# SSH Configuration
# Generated by dotfiles setup

# Global Defaults
Host *
    AddKeysToAgent yes
    IdentitiesOnly yes
    ServerAliveInterval 60
    ServerAliveCountMax 3
EOF

        # UseKeychain is macOS-only
        if [ "$(detect_os_family)" = "macos" ]; then
            cat >> "$SSH_DIR/config" << 'EOF'

# macOS Keychain
Host *
    UseKeychain yes
EOF
        fi

        cat >> "$SSH_DIR/config" << 'EOF'

# Personal GitHub
Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519

EOF
        chmod 600 "$SSH_DIR/config"
        success "Created ~/.ssh/config"
    fi
}

add_ssh_host() {
    local host_alias="$1"
    local key_file="$2"
    local comment="$3"

    if has_ssh_host "$host_alias"; then
        warning "SSH host '$host_alias' already exists, skipping..."
        return
    fi

    cat >> "$SSH_DIR/config" << EOF

# $comment
Host $host_alias
    HostName github.com
    User git
    IdentityFile ~/.ssh/$key_file
EOF

    success "Added SSH host: $host_alias"
}

add_git_url_rewrite() {
    local host_alias="$1"
    local org_name="$2"

    if has_git_url_rewrite "$org_name"; then
        warning "Git URL rewrite for '$org_name' already exists, skipping..."
        return
    fi

    # Add to gitconfig
    git config --global url."git@${host_alias}:${org_name}/".insteadOf "git@github.com:${org_name}/"

    success "Added Git URL rewrite: github.com:${org_name}/ -> ${host_alias}:${org_name}/"
}

add_git_includeif() {
    local dir_path="$1"
    local config_file="$2"
    local email="$3"
    local name="${4:-}"

    # Ensure directory path ends with /
    [[ "$dir_path" != */ ]] && dir_path="${dir_path}/"

    # Create the separate gitconfig file
    if [ ! -f "$config_file" ]; then
        cat > "$config_file" << EOF
[user]
    email = $email
EOF
        if [ -n "$name" ]; then
            echo "    name = $name" >> "$config_file"
        fi
        success "Created $config_file"
    fi

    # Check if includeIf already exists
    if grep -q "gitdir:$dir_path" "$GITCONFIG" 2>/dev/null; then
        warning "includeIf for '$dir_path' already exists, skipping..."
        return
    fi

    # Add includeIf to main gitconfig
    git config --global --add includeIf."gitdir:$dir_path".path "$config_file"

    success "Added includeIf: $dir_path -> $config_file"
}

# ============================================================================
# Git Global Config Setup
# ============================================================================

setup_git_global() {
    local current_name=$(git config --global user.name 2>/dev/null || echo "")
    local current_email=$(git config --global user.email 2>/dev/null || echo "")

    # Check if both are set
    if [ -n "$current_name" ] && [ -n "$current_email" ]; then
        echo "Current global Git config:"
        echo "  Name:  $current_name"
        echo "  Email: $current_email"
        echo ""
        read -p "Keep these settings? [Y/n]: " keep_settings
        if [[ "$keep_settings" =~ ^[Nn] ]]; then
            current_name=""
            current_email=""
        else
            return 0
        fi
    fi

    # Prompt for name if not set
    if [ -z "$current_name" ]; then
        while [ -z "$current_name" ]; do
            read -p "Enter your Git username (for personal/default account): " current_name
            if [ -z "$current_name" ]; then
                warning "Username cannot be empty"
            fi
        done
        git config --global user.name "$current_name"
        success "Set global user.name: $current_name"
    fi

    # Prompt for email if not set
    if [ -z "$current_email" ]; then
        while [ -z "$current_email" ]; do
            read -p "Enter your Git email (for personal/default account): " current_email
            if [ -z "$current_email" ]; then
                warning "Email cannot be empty"
            fi
        done
        git config --global user.email "$current_email"
        success "Set global user.email: $current_email"
    fi

    echo ""
}

# ============================================================================
# Interactive Setup
# ============================================================================

setup_wsl_ssh() {
    if ! is_wsl; then
        return
    fi

    echo ""
    info "WSL2 environment detected."
    echo ""
    echo "On WSL2, SSH keys managed by 1Password (or Windows SSH agent) require"
    echo "Git to use the Windows ssh.exe instead of the Linux one."
    echo ""

    local current_cmd
    current_cmd=$(git config --global core.sshCommand 2>/dev/null || echo "")

    if [ "$current_cmd" = "ssh.exe" ]; then
        success "git core.sshCommand is already set to ssh.exe"
        return
    fi

    read -p "Use Windows ssh.exe for Git? (required for 1Password SSH keys) [Y/n]: " use_ssh_exe
    if [[ ! "$use_ssh_exe" =~ ^[Nn] ]]; then
        git config --global core.sshCommand ssh.exe
        success "Set git core.sshCommand = ssh.exe"
    else
        info "Skipped. You can set it later with: git config --global core.sshCommand ssh.exe"
    fi
}

interactive_setup() {
    echo ""
    echo "======================================"
    echo "  SSH Multi-Account Setup"
    echo "======================================"
    echo ""

    # WSL2: configure Git to use Windows ssh.exe for 1Password agent
    setup_wsl_ssh

    # Step 1: Ensure global git config is set
    info "Step 1: Checking global Git configuration..."
    echo ""
    setup_git_global

    # Step 2: Ensure SSH directory exists
    info "Step 2: Setting up SSH configuration..."
    mkdir -p "$SSH_DIR"
    chmod 700 "$SSH_DIR"

    # Setup SSH config header
    setup_ssh_config_header

    # Step 3: Scan for additional keys
    info "Step 3: Scanning for additional SSH keys..."
    echo ""
    local extra_keys=($(scan_ssh_keys))

    if [ ${#extra_keys[@]} -eq 0 ]; then
        info "No additional SSH keys found (besides default id_ed25519/id_rsa)"
        echo ""
        echo "To add a work/organization account:"
        echo "  1. Copy your SSH key to ~/.ssh/ (e.g., id_ed25519_work)"
        echo "  2. Run this script again"
        echo ""
        return
    fi

    echo "Found additional SSH keys:"
    for key in "${extra_keys[@]}"; do
        echo "  - $key"
    done
    echo ""

    # Process each key
    for key_name in "${extra_keys[@]}"; do
        echo "----------------------------------------"
        echo "Configuring: $key_name"
        echo "----------------------------------------"

        # Ask for SSH host alias
        local default_alias=$(echo "$key_name" | sed 's/id_ed25519_/github-/' | sed 's/id_rsa_/github-/')
        read -p "SSH host alias [$default_alias]: " host_alias
        host_alias="${host_alias:-$default_alias}"

        # Ask for organization name
        read -p "GitHub organization name: " org_name

        if [ -z "$org_name" ]; then
            warning "No organization name provided, skipping URL rewrite..."
        fi

        # Get default values from global git config
        local default_name=$(git config --global user.name 2>/dev/null || echo "")
        local default_email=$(git config --global user.email 2>/dev/null || echo "")

        # Ask for git name
        if [ -n "$default_name" ]; then
            read -p "Git username for this account [$default_name]: " work_name
            work_name="${work_name:-$default_name}"
        else
            read -p "Git username for this account: " work_name
        fi

        # Ask for work email
        if [ -n "$default_email" ]; then
            read -p "Git email for this account [$default_email]: " work_email
            work_email="${work_email:-$default_email}"
        else
            read -p "Git email for this account: " work_email
        fi

        # Ask for project directory
        read -p "Project directory (e.g., ~/Projects/Work): " project_dir

        # Expand tilde
        project_dir="${project_dir/#\~/$HOME}"

        # Add SSH host
        add_ssh_host "$host_alias" "$key_name" "$org_name"

        # Add Git URL rewrite
        if [ -n "$org_name" ]; then
            add_git_url_rewrite "$host_alias" "$org_name"
        fi

        # Add includeIf for directory-based identity
        if [ -n "$project_dir" ] && [ -n "$work_email" ]; then
            local config_suffix=$(echo "$host_alias" | sed 's/github-//')
            local config_file="$HOME/.gitconfig-$config_suffix"
            add_git_includeif "$project_dir" "$config_file" "$work_email" "$work_name"
        fi

        echo ""
    done

    echo "======================================"
    echo "  Setup Complete!"
    echo "======================================"
    echo ""
    echo "Your SSH config:"
    echo "  ~/.ssh/config"
    echo ""
    echo "Your Git config:"
    echo "  ~/.gitconfig"
    echo ""
    echo "Test your SSH connections:"
    for key_name in "${extra_keys[@]}"; do
        local alias=$(echo "$key_name" | sed 's/id_ed25519_/github-/' | sed 's/id_rsa_/github-/')
        echo "  ssh -T git@$alias"
    done
    echo ""
}

# ============================================================================
# Main
# ============================================================================

case "${1:-}" in
    --help|-h)
        echo "Usage: $0 [--interactive|--scan]"
        echo ""
        echo "Options:"
        echo "  --interactive  Run interactive setup (default)"
        echo "  --scan         Just scan and list SSH keys"
        ;;
    --scan)
        keys=($(scan_ssh_keys))
        if [ ${#keys[@]} -eq 0 ]; then
            echo "No additional SSH keys found"
        else
            echo "Found SSH keys:"
            for key in "${keys[@]}"; do
                echo "  - $key"
            done
        fi
        ;;
    *)
        interactive_setup
        ;;
esac
